<?php

/**
 * @file
 * TBC StarRez integration module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tbc_custom_fields_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.tbc_custom_fields':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('TBC - Custom fields') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tbc_custom_fields_theme($existing, $type, $theme, $path) {
  return [
    'accordion' => [
      'variables' => ['content' => NULL],
      'template' => 'accordion',
    ],
  ];
}
