<?php

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function vfi_api_node_insert(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->bundle() == 'message') {
    $field_type = $entity->get('field_type')->getString();

    $definitions = $entity->getFieldDefinitions();
    /** @var \Drupal\field\Entity\FieldConfig $field_type_definition */
    $field_type_definition = $definitions['field_type'];
    $allowed_values = $field_type_definition->getSetting('allowed_values');

    $readableType = $allowed_values[$field_type];


    $date = $entity->get('field_message_date')->getString();
    $timestamp = strtotime($date);
    $formatted_date = \Drupal::service('date.formatter')
      ->format($timestamp, 'custom', 'd F Y');

    /** @var \Drupal\file\Entity\File $mediaFile */
    $mediaEntity = $entity->get('field_sermon_file')
      ->first()
      ->get('entity')
      ->getTarget()
      ->getValue();

    if (!empty($mediaEntity)) {
      $fileEntity = $mediaEntity->get('field_media_audio_file')
        ->first()
        ->get('entity')
        ->getTarget()
        ->getValue();

      $media_url = file_create_url($fileEntity->getFileUri());

      //API URL of FCM
      $url = 'https://fcm.googleapis.com/fcm/send';

      $api_key = 'AAAASky5KRI:APA91bFfMg-4lw6DFK3IjJMRBIhjxd0QoLHRoaDcYyqpWvBPaAlX6abI7Zp1e_MVGgwFAyzs1N-lV68Ncj7nw38wDeR1WCCXodpmVGoLbuDQgiKorHH7j1DxCu6X1AG4mCeUioFKVP0x';

      $fields = array(
        'to' => '/topics/vfi-notification-topic',
        'notification' => array(
          "title" => 'New Upload',
          "body" => 'A message titled "' . $entity->label() . '" has just been uploaded to the "' . $readableType . '" section',
          "android_channel_id" => 'vfi-media-centre-notifications',
        ),
        'data' => [
          'title' => $entity->label(),
          'id' => $entity->id(),
          'link' => $media_url,
          'date' => $formatted_date
        ],
      );

      //header includes Content type and api key
      $headers = array(
        'Content-Type:application/json',
        'Authorization:key=' . $api_key
      );

      $ch = curl_init();
      curl_setopt($ch, CURLOPT_URL, $url);
      curl_setopt($ch, CURLOPT_POST, true);
      curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
      curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
      curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
      curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
      $result = curl_exec($ch);
      if ($result === FALSE) {
        die('FCM Send Error: ' . curl_error($ch));
      }
      curl_close($ch);
    }
  }
}
